(ns examples.spring-to-boing-1
  (:use [boing.bean] [clojure.contrib.def]))

(def *tmo* nil)
(def *username* nil)
(def *password* nil)
(def *mappings* (atom nil))

(defbean :alerterBean "higiebus.bus.protocol.V2.alerts.Alerter" :s-vals {:producer :alertProducerBean :facility "UVISADAPTER"})

(defbean :connectionFactoryBean "org.apache.activemq.ActiveMQConnectionFactory"
  :s-vals {:brokerURL (fn [] (format "failover:(tcp://brkmaster:61616?connectionTimeout=%s,tcp://brkslave:61616?connectionTimeout=%s)?randomize=false"))})

(defbean :cacheProviderBean "net.sf.ehcache.hibernate.EhCacheProvider")

(defbean :defaultEventProcessorBean "higiebus.adaptors.hms.events.processors.IgnoredEventProcessor" :s-vals {:alerter :alerterBean})

(defbean :hmsInboundEventFactoryBean "higiebus.adaptors.hms.uvis.events.inbound.UvisInboundEventFactory"
  :s-vals {:alerter :alerterBean :componentStatus :componentMonitorBean :hmsCache :hmsCacheBean :hmsParameters :hmsParametersBean})

(defbean :processorContextBean "higiebus.adaptors.hms.uvis.events.processors.ProcessorContext" :s-vals {:busCache :busCacheBean})

;; Define a bunch of similar beans
(let [beans [["AdmitPatientProcessorBean" "higiebus.adaptors.hms.uvis.events.processors.AdmitPatientProcessor"]
             ["DischargePatientProcessorBean" "higiebus.adaptors.hms.uvis.events.processors.DischargePatientProcessor"]
             ["UpdatePatientProcessorBean" "higiebus.adaptors.hms.uvis.events.processors.UpdatePatientInformationProcessor"]
             ["RequestProcessorBean" "higiebus.adaptors.hms.uvis.events.processors.RequestProcessor"]
             ["ObservationProcessorBean" "higiebus.adaptors.hms.uvis.events.processors.ObservationProcessor"]
             ["VisitProcessorBean" "higiebus.adaptors.hms.uvis.events.processors.UpdateVisitsProcessor"]
             ["CensusProcessorBean" "higiebus.adaptors.hms.uvis.events.processors.HospitalCensusProcessor"]]]
  (dorun (map
           (fn [[bname bclass]]
             (defbean bname bclass
               :s-vals { :hmsSessionFactory :hmsSessionFactoryBean :processorContext :processorContextBean
                        :hmsCache :hmsCacheBean :hmsParameters :hmsParametersBean :alerter :alerterBean })) beans)))

(defbean :hmsParametersBean "higiebus.adaptors.hms.uvis.HMSUvisParameters" :mode :singleton
  :s-vals {:senderApplicationName "HIGIEBUS" :senderApplicationInstance "PROTOTYPE"
           :radiologyAreas {28 "ECHO" 21 "RX-GA" 22 "RX-PA" 27 "TORE"}
           :radiologyAnswersExamDescriptions
           { 897 "Examen spécifiques" 878 "DONNÉES PERTINENTES ET/OU SIGNES CLINIQUES"
            901 "DONNÉES PERTINENTES ET/OU SIGNES CLINIQUES" 922 "DONNÉES PERTINENTES ET/OU SIGNES CLINIQUES" 
            1809 "DONNÉES PERTINENTES ET/OU SIGNES CLINIQUES"}
           :requestUpdateStatusFilter
           { "NEW" false "REQUESTED" true "ACCEPTED" true "MODIFIED" true "SCHEDULED" true "PRELIMINARY" true "CANCELLED" false
            "REJECTED" true "COMPLETE" true "AMENDED" true "PERFORMED" true "ADDENDED" true}})

(defbean :HMSPatientDaoBean "higiebus.adaptors.hms.uvis.dao.UvisPatientDao")
(defbean :HMSClientDaoBean "higiebus.adaptors.hms.uvis.dao.UvisClientDao")
(defbean :HMSOrderDaoBean "higiebus.adaptors.hms.uvis.dao.UvisOrderDao")
(defbean :HMSEmployeeDaoBean "higiebus.adaptors.hms.uvis.dao.UvisEmployeeDao")
(defbean :HMSRequestDaoBean "higiebus.adaptors.hms.uvis.dao.UvisRequestDao")
(defbean :HMSResultDaoBean "higiebus.adaptors.hms.uvis.dao.UvisResultDao")
(defbean :HMSEpisodeDaoBean "higiebus.adaptors.hms.uvis.dao.UvisEpisodeDao")
(defbean :HMSRequestAnswerDaoBean "higiebus.adaptors.hms.uvis.dao.UvisRequestAnswerDao")
(defbean :HMSDiagnosisDaoBean "higiebus.adaptors.hms.uvis.dao.UvisDiagnosisDao")
(defbean :HMSHospitalCensusDaoBean "higiebus.adaptors.hms.uvis.dao.UvisHospitalCensusDao")
(defbean :hmsCacheFactoryBean "higiebus.adaptors.hms.cache.HMSCacheFactory")
(defbean :hmsCacheBean "higiebus.adaptors.hms.cache.HMSCacheFactory" :mode :singleton :post (fn [x] (.createInstance x)))


(defbean :hmsDataSourceBean "higiebus.adaptors.hms.HMSDataSource"
  :s-vals { :driverClassName "oracle.jdbc.driver.OracleDriver" :url "jdbc:oracle:thin:@10.0.1.54:1521:uvistest"
           :username (fn [] *username*) :password (fn [] *password*)
           :maxWait 10000 :testWhileIdle true	:testOnBorrow true
           :validationQuery "select 1 from dual" :maxActive 20 :maxIdle 8 :minIdle 3 :timeBetweenEvictionRunsMillis 900000
           :numTestsPerEvictionRun 50 :minEvictableIdleTimeMillis 1800000
           :mappingResources
           (list "uvis/dao/mappings/Frm50EnabledRoles.hbm.xml" "uvis/dao/mappings/PlanTable.hbm.xml"
							"uvis/dao/mappings/PyxisExcludedMachinesM.hbm.xml" "uvis/dao/mappings/PyxisInsert.hbm.xml"
							"uvis/dao/mappings/QuestTempExplain.hbm.xml" "uvis/dao/mappings/UdemReportDefinitions.hbm.xml"
							"uvis/dao/mappings/UdemReportLabels.hbm.xml" "uvis/dao/mappings/UdemReportMrQuestions.hbm.xml"
							"uvis/dao/mappings/UdemUvisProductLineM.hbm.xml" "uvis/dao/mappings/UvisAccountingSetup.hbm.xml"
							"uvis/dao/mappings/UvisAdjTypeServSect.hbm.xml"
							"uvis/dao/mappings/UvisAdjustmentTypeM.hbm.xml"
							"uvis/dao/mappings/UvisApplicationM.hbm.xml"
							"uvis/dao/mappings/UvisApplicationUserX.hbm.xml"
							"uvis/dao/mappings/UvisApptAreaM.hbm.xml"
							"uvis/dao/mappings/UvisApptDtl.hbm.xml"
							"uvis/dao/mappings/UvisApptDtlWorking.hbm.xml"
							"uvis/dao/mappings/UvisApptEndingV.hbm.xml"
							"uvis/dao/mappings/UvisApptHdr.hbm.xml"
							"uvis/dao/mappings/UvisApptReminderStatusM.hbm.xml"
							"uvis/dao/mappings/UvisApptResAlloc.hbm.xml"
							"uvis/dao/mappings/UvisApptResourceM.hbm.xml"
							"uvis/dao/mappings/UvisApptRotationM.hbm.xml"
							"uvis/dao/mappings/UvisApptServiceRoleX.hbm.xml"
							"uvis/dao/mappings/UvisApptTemplateDtl.hbm.xml"
							"uvis/dao/mappings/UvisApptTemplateHdr.hbm.xml"
							"uvis/dao/mappings/UvisApptTypesM.hbm.xml"
							"uvis/dao/mappings/UvisAreaUserCatM.hbm.xml"
							"uvis/dao/mappings/UvisAreaUserX.hbm.xml"
							"uvis/dao/mappings/UvisAsaqBatchDtl.hbm.xml"
							"uvis/dao/mappings/UvisAsaqBatchHdr.hbm.xml"
							"uvis/dao/mappings/UvisAsaqOrderDtl.hbm.xml"
							"uvis/dao/mappings/UvisAsaqSetupM.hbm.xml"
							"uvis/dao/mappings/UvisAsaqTariffM.hbm.xml"
							"uvis/dao/mappings/UvisAsaqTariffPricing.hbm.xml"
							"uvis/dao/mappings/UvisAuthorizationTypeM.hbm.xml"
							"uvis/dao/mappings/UvisAvmaCategoryM.hbm.xml"
							"uvis/dao/mappings/UvisBankAcctTypeM.hbm.xml"
							"uvis/dao/mappings/UvisBlockGroupM.hbm.xml"
							"uvis/dao/mappings/UvisBlockSchd.hbm.xml"
							"uvis/dao/mappings/UvisBoardingCharges.hbm.xml"
							"uvis/dao/mappings/UvisBreedsM.hbm.xml"
							"uvis/dao/mappings/UvisBreedsSynX.hbm.xml"
							"uvis/dao/mappings/UvisCashierLog.hbm.xml"
							"uvis/dao/mappings/UvisCashRegister.hbm.xml"
							"uvis/dao/mappings/UvisCcardTypesM.hbm.xml"
							"uvis/dao/mappings/UvisCdmErrorLog.hbm.xml"
							"uvis/dao/mappings/UvisCdmErrorM.hbm.xml"
							"uvis/dao/mappings/UvisCdmErrorWorking.hbm.xml"
							"uvis/dao/mappings/UvisCdmLog.hbm.xml"
							"uvis/dao/mappings/UvisCdmPcFees.hbm.xml"
							"uvis/dao/mappings/UvisCdmPostingH.hbm.xml"
							"uvis/dao/mappings/UvisCdmTracking.hbm.xml"
							"uvis/dao/mappings/UvisCdmWorking.hbm.xml"
							"uvis/dao/mappings/UvisChargeAreaM.hbm.xml"
							"uvis/dao/mappings/UvisCitationM.hbm.xml"
							"uvis/dao/mappings/UvisCitationResults.hbm.xml"
							"uvis/dao/mappings/UvisClClientV.hbm.xml"
							"uvis/dao/mappings/UvisClContainerMV.hbm.xml"
							"uvis/dao/mappings/UvisClEpisodeResultValueV.hbm.xml"
							"uvis/dao/mappings/UvisClientContactV.hbm.xml"
							"uvis/dao/mappings/UvisClientCredit.hbm.xml"
							"uvis/dao/mappings/UvisClientCreditLog.hbm.xml"
							"uvis/dao/mappings/UvisClient.hbm.xml"
							"uvis/dao/mappings/UvisClientLog.hbm.xml"
							"uvis/dao/mappings/UvisClientPatientV.hbm.xml"
							"uvis/dao/mappings/UvisClientRdvmDistinctV.hbm.xml"
							"uvis/dao/mappings/UvisClientRelationshipM.hbm.xml"
							"uvis/dao/mappings/UvisClientToClientX.hbm.xml"
							"uvis/dao/mappings/UvisClientTypeM.hbm.xml"
							"uvis/dao/mappings/UvisClInterfaceV.hbm.xml"
							"uvis/dao/mappings/UvisClLocationMV.hbm.xml"
							"uvis/dao/mappings/UvisClPatientV.hbm.xml"
							"uvis/dao/mappings/UvisClReqContainerDtlV.hbm.xml"
							"uvis/dao/mappings/UvisClReqContainerHdrV.hbm.xml"
							"uvis/dao/mappings/UvisClReqitemAnswersV.hbm.xml"
							"uvis/dao/mappings/UvisClRequestItemsV.hbm.xml"
							"uvis/dao/mappings/UvisClRequestV.hbm.xml"
							"uvis/dao/mappings/UvisClResultTestsV.hbm.xml"
							"uvis/dao/mappings/UvisClResultV.hbm.xml"
							"uvis/dao/mappings/UvisClRtestMV.hbm.xml"
							"uvis/dao/mappings/UvisClSetup.hbm.xml"
							"uvis/dao/mappings/UvisClSexMV.hbm.xml"
							"uvis/dao/mappings/UvisClSpeciesMV.hbm.xml"
							"uvis/dao/mappings/UvisClTestContainerV.hbm.xml"
							"uvis/dao/mappings/UvisClTestMV.hbm.xml"
							"uvis/dao/mappings/UvisClTestQuestionXV.hbm.xml"
							"uvis/dao/mappings/UvisClWkstnRtestXV.hbm.xml"
							"uvis/dao/mappings/UvisClWorkstationMV.hbm.xml"
							"uvis/dao/mappings/UvisColorsM.hbm.xml"
							"uvis/dao/mappings/UvisColumnDef.hbm.xml"
							"uvis/dao/mappings/UvisComments.hbm.xml"
							"uvis/dao/mappings/UvisCommentsSourceType.hbm.xml"
							"uvis/dao/mappings/UvisContract.hbm.xml"
							"uvis/dao/mappings/UvisContractPoSetup.hbm.xml"
							"uvis/dao/mappings/UvisContractPoTypeM.hbm.xml"
							"uvis/dao/mappings/UvisCreditDebitCodesM.hbm.xml"
							"uvis/dao/mappings/UvisCreditDebitReport.hbm.xml"
							"uvis/dao/mappings/UvisDcChargesCurrMonthV.hbm.xml"
							"uvis/dao/mappings/UvisDcNewChargesV.hbm.xml"
							"uvis/dao/mappings/UvisDcReportLogDtl.hbm.xml"
							"uvis/dao/mappings/UvisDcReportLogHdr.hbm.xml"
							"uvis/dao/mappings/UvisDeposit.hbm.xml"
							"uvis/dao/mappings/UvisDepositV.hbm.xml"
							"uvis/dao/mappings/UvisDiagnosisProductsM.hbm.xml"
							"uvis/dao/mappings/UvisDiagnosisSectionX.hbm.xml"
							"uvis/dao/mappings/UvisDiagnosisServiceX.hbm.xml"
							"uvis/dao/mappings/UvisDiagnosisSynonym.hbm.xml"
							"uvis/dao/mappings/UvisDirectOrdersV.hbm.xml"
							"uvis/dao/mappings/UvisDischElementsM.hbm.xml"
							"uvis/dao/mappings/UvisDischStatusM.hbm.xml"
							"uvis/dao/mappings/UvisDischSub2ElementsM.hbm.xml"
							"uvis/dao/mappings/UvisDischSubElementsM.hbm.xml"
							"uvis/dao/mappings/UvisDischTemplate.hbm.xml"
							"uvis/dao/mappings/UvisDischTemplElmntsX.hbm.xml"
							"uvis/dao/mappings/UvisDischTemplServiceX.hbm.xml"
							"uvis/dao/mappings/UvisDischTemplSub2ElmntsX.hbm.xml"
							"uvis/dao/mappings/UvisDischTemplSubElmntsX.hbm.xml"
							"uvis/dao/mappings/UvisDlAccessionAnimalXV.hbm.xml"
							"uvis/dao/mappings/UvisDlAccessionNoV.hbm.xml"
							"uvis/dao/mappings/UvisDlAccessionsV.hbm.xml"
							"uvis/dao/mappings/UvisDlClientMV.hbm.xml"
							"uvis/dao/mappings/UvisDlEpisodeTestV.hbm.xml"
							"uvis/dao/mappings/UvisDlInterfaceV.hbm.xml"
							"uvis/dao/mappings/UvisDlLabelDtlFmtV.hbm.xml"
							"uvis/dao/mappings/UvisDlLabelDtlV.hbm.xml"
							"uvis/dao/mappings/UvisDlLabelHdrV.hbm.xml"
							"uvis/dao/mappings/UvisDlRdvmV.hbm.xml"
							"uvis/dao/mappings/UvisDlRequestAccessionXV.hbm.xml"
							"uvis/dao/mappings/UvisDlSectionM.hbm.xml"
							"uvis/dao/mappings/UvisDlSetup.hbm.xml"
							"uvis/dao/mappings/UvisDlSpecimenCodeV.hbm.xml"
							"uvis/dao/mappings/UvisDlTestsV.hbm.xml"
							"uvis/dao/mappings/UvisDlValidationListItemV.hbm.xml"
							"uvis/dao/mappings/UvisDrugClassM.hbm.xml"
							"uvis/dao/mappings/UvisDvmIncomeData.hbm.xml"
							"uvis/dao/mappings/UvisDvmIncomeHeadings.hbm.xml"
							"uvis/dao/mappings/UvisEmployee.hbm.xml"
							"uvis/dao/mappings/UvisEmployeeStatusM.hbm.xml"
							"uvis/dao/mappings/UvisEmployeeTypeM.hbm.xml"
							"uvis/dao/mappings/UvisEmpNameV.hbm.xml"
							"uvis/dao/mappings/UvisEodAdjDtl.hbm.xml"
							"uvis/dao/mappings/UvisEodAvma.hbm.xml"
							"uvis/dao/mappings/UvisEodDebit.hbm.xml"
							"uvis/dao/mappings/UvisEodDvmAccessionBup.hbm.xml"
							"uvis/dao/mappings/UvisEodDvmAccession.hbm.xml"
							"uvis/dao/mappings/UvisEodExpenseDtl.hbm.xml"
							"uvis/dao/mappings/UvisEodHospitalAccession.hbm.xml"
							"uvis/dao/mappings/UvisEodIncome.hbm.xml"
							"uvis/dao/mappings/UvisEodProcLogHolder.hbm.xml"
							"uvis/dao/mappings/UvisEodProratedExpense.hbm.xml"
							"uvis/dao/mappings/UvisEodSalesTax.hbm.xml"
							"uvis/dao/mappings/UvisEodSectionAccession.hbm.xml"
							"uvis/dao/mappings/UvisEodServiceAccession.hbm.xml"
							"uvis/dao/mappings/UvisEodStatus.hbm.xml"
							"uvis/dao/mappings/UvisEodTotals.hbm.xml"
							"uvis/dao/mappings/UvisEomAdjDtl.hbm.xml"
							"uvis/dao/mappings/UvisEomAvma.hbm.xml"
							"uvis/dao/mappings/UvisEomDvmAccession.hbm.xml"
							"uvis/dao/mappings/UvisEomExpenseDtl.hbm.xml"
							"uvis/dao/mappings/UvisEomHospitalAccession.hbm.xml"
							"uvis/dao/mappings/UvisEomIncome.hbm.xml"
							"uvis/dao/mappings/UvisEomProcessingLog.hbm.xml"
							"uvis/dao/mappings/UvisEomProratedExpenses.hbm.xml"
							"uvis/dao/mappings/UvisEomSalesTax.hbm.xml"
							"uvis/dao/mappings/UvisEomSectionAccession.hbm.xml"
							"uvis/dao/mappings/UvisEomServiceAccession.hbm.xml"
							"uvis/dao/mappings/UvisEomStatus.hbm.xml"
							"uvis/dao/mappings/UvisEomStmntLog.hbm.xml"
							"uvis/dao/mappings/UvisEomTotals.hbm.xml"
							"uvis/dao/mappings/UvisEoyAdjDtl.hbm.xml"
							"uvis/dao/mappings/UvisEoyAvma.hbm.xml"
							"uvis/dao/mappings/UvisEoyExpenseDtl.hbm.xml"
							"uvis/dao/mappings/UvisEoyStatus.hbm.xml"
							"uvis/dao/mappings/UvisEoyTotals.hbm.xml"
							"uvis/dao/mappings/UvisErrorMessage.hbm.xml"
							"uvis/dao/mappings/UvisEstimateCategory.hbm.xml"
							"uvis/dao/mappings/UvisEstimateDiagnosis.hbm.xml"
							"uvis/dao/mappings/UvisEstimateDiagnosisM.hbm.xml"
							"uvis/dao/mappings/UvisEstimateHdr.hbm.xml"
							"uvis/dao/mappings/UvisEstimateLog.hbm.xml"
							"uvis/dao/mappings/UvisEstimateProducts.hbm.xml"
							"uvis/dao/mappings/UvisExistingSchdV.hbm.xml"
							"uvis/dao/mappings/UvisExpenseCodeM.hbm.xml"
							"uvis/dao/mappings/UvisExpenses.hbm.xml"
							"uvis/dao/mappings/UvisExpenseTypeM.hbm.xml"
							"uvis/dao/mappings/UvisExtDeviceCatM.hbm.xml"
							"uvis/dao/mappings/UvisExtDeviceM.hbm.xml"
							"uvis/dao/mappings/UvisExtDeviceX.hbm.xml"
							"uvis/dao/mappings/UvisExternalBillingFile.hbm.xml"
							"uvis/dao/mappings/UvisExternalDocs.hbm.xml"
							"uvis/dao/mappings/UvisFaxSetup.hbm.xml"
							"uvis/dao/mappings/UvisGenericReportDfn.hbm.xml"
							"uvis/dao/mappings/UvisHospitalCensus.hbm.xml"
							"uvis/dao/mappings/UvisHospitalCensusLog.hbm.xml"
							"uvis/dao/mappings/UvisHospitalClinicM.hbm.xml"
							"uvis/dao/mappings/UvisHospitalWardCageM.hbm.xml"
							"uvis/dao/mappings/UvisHospitalWardM.hbm.xml"
							"uvis/dao/mappings/UvisInterfaceErrorLog.hbm.xml"
							"uvis/dao/mappings/UvisInterface.hbm.xml"
							"uvis/dao/mappings/UvisInventoryAreaM.hbm.xml"
							"uvis/dao/mappings/UvisInventory.hbm.xml"
							"uvis/dao/mappings/UvisInventoryLocation.hbm.xml"
							"uvis/dao/mappings/UvisInventoryLog.hbm.xml"
							"uvis/dao/mappings/UvisInventoryProductV.hbm.xml"
							"uvis/dao/mappings/UvisInventorySetup.hbm.xml"
							"uvis/dao/mappings/UvisInventoryTransTypeM.hbm.xml"
							"uvis/dao/mappings/UvisInventoryUserX.hbm.xml"
							"uvis/dao/mappings/UvisInvoiceBak1.hbm.xml"
							"uvis/dao/mappings/UvisInvoiceBak2.hbm.xml"
							"uvis/dao/mappings/UvisInvoiceBak.hbm.xml"
							"uvis/dao/mappings/UvisInvoiceBalanceDif1.hbm.xml"
							"uvis/dao/mappings/UvisInvoiceBalanceDif.hbm.xml"
							"uvis/dao/mappings/UvisInvoiceDc.hbm.xml"
							"uvis/dao/mappings/UvisInvoice.hbm.xml"
							"uvis/dao/mappings/UvisInvoiceH.hbm.xml"
							"uvis/dao/mappings/UvisInvoiceLog.hbm.xml"
							"uvis/dao/mappings/UvisInvoiceTransTypeM.hbm.xml"
							"uvis/dao/mappings/UvisInvRequestUnitsTypeM.hbm.xml"
							"uvis/dao/mappings/UvisInvXferProductV.hbm.xml"
							"uvis/dao/mappings/UvisJavaDirList.hbm.xml"
							"uvis/dao/mappings/UvisLabelCount.hbm.xml"
							"uvis/dao/mappings/UvisLoss.hbm.xml"
							"uvis/dao/mappings/UvisManufacturerM.hbm.xml"
							"uvis/dao/mappings/UvisMedRecordCategoryM.hbm.xml"
							"uvis/dao/mappings/UvisMedRecord.hbm.xml"
							"uvis/dao/mappings/UvisMedRecordLog.hbm.xml"
							"uvis/dao/mappings/UvisMedRecordResolution.hbm.xml"
							"uvis/dao/mappings/UvisMedRecordResolutionM.hbm.xml"
							"uvis/dao/mappings/UvisMenuItem.hbm.xml"
							"uvis/dao/mappings/UvisMenuM.hbm.xml"
							"uvis/dao/mappings/UvisMessage.hbm.xml"
							"uvis/dao/mappings/UvisMessageLevel.hbm.xml"
							"uvis/dao/mappings/UvisMessageLog.hbm.xml"
							"uvis/dao/mappings/UvisMessageType.hbm.xml"
							"uvis/dao/mappings/UvisModuleCatM.hbm.xml"
							"uvis/dao/mappings/UvisModuleItemDisplay.hbm.xml"
							"uvis/dao/mappings/UvisModuleItemDisplayTemp.hbm.xml"
							"uvis/dao/mappings/UvisModuleM.hbm.xml"
							"uvis/dao/mappings/UvisModuleOptions.hbm.xml"
							"uvis/dao/mappings/UvisModulePriv.hbm.xml"
							"uvis/dao/mappings/UvisModulePrivUserX.hbm.xml"
							"uvis/dao/mappings/UvisModuleTypeM.hbm.xml"
							"uvis/dao/mappings/UvisMrAddtlChgsM.hbm.xml"
							"uvis/dao/mappings/UvisMrAddtlInfoM.hbm.xml"
							"uvis/dao/mappings/UvisMrAddtlRsltsLog.hbm.xml"
							"uvis/dao/mappings/UvisMrAnatomicSiteM.hbm.xml"
							"uvis/dao/mappings/UvisMrAnatomicSiteX.hbm.xml"
							"uvis/dao/mappings/UvisMrAnswerCodeM.hbm.xml"
							"uvis/dao/mappings/UvisMrAnswers.hbm.xml"
							"uvis/dao/mappings/UvisMrAnswersMods.hbm.xml"
							"uvis/dao/mappings/UvisMrAnswerTypeM.hbm.xml"
							"uvis/dao/mappings/UvisMrAnswerV.hbm.xml"
							"uvis/dao/mappings/UvisMrAreaBillX.hbm.xml"
							"uvis/dao/mappings/UvisMrAreaM.hbm.xml"
							"uvis/dao/mappings/UvisMrAreaNotifyX.hbm.xml"
							"uvis/dao/mappings/UvisMrAreaOptionsM.hbm.xml"
							"uvis/dao/mappings/UvisMrAreaOptionsSetM.hbm.xml"
							"uvis/dao/mappings/UvisMrAreaOptionsSetX.hbm.xml"
							"uvis/dao/mappings/UvisMrAreaReqResultStatus.hbm.xml"
							"uvis/dao/mappings/UvisMrBillingExc.hbm.xml"
							"uvis/dao/mappings/UvisMrBodySystemsM.hbm.xml"
							"uvis/dao/mappings/UvisMrBodySystemsX.hbm.xml"
							"uvis/dao/mappings/UvisMrCaseTransferList.hbm.xml"
							"uvis/dao/mappings/UvisMrChartPullLog.hbm.xml"
							"uvis/dao/mappings/UvisMrComments.hbm.xml"
							"uvis/dao/mappings/UvisMrCommentsMods.hbm.xml"
							"uvis/dao/mappings/UvisMrCommEvent.hbm.xml"
							"uvis/dao/mappings/UvisMrCommLog.hbm.xml"
							"uvis/dao/mappings/UvisMrCommTypeM.hbm.xml"
							"uvis/dao/mappings/UvisMrCommTypeStatusM.hbm.xml"
							"uvis/dao/mappings/UvisMrCommWorklist.hbm.xml"
							"uvis/dao/mappings/UvisMrCommWorklistLog.hbm.xml"
							"uvis/dao/mappings/UvisMrDatatype.hbm.xml"
							"uvis/dao/mappings/UvisMrDcInstructionsX.hbm.xml"
							"uvis/dao/mappings/UvisMrDiagnosis.hbm.xml"
							"uvis/dao/mappings/UvisMrDiagnosisMods.hbm.xml"
							"uvis/dao/mappings/UvisMrDiagnosisX.hbm.xml"
							"uvis/dao/mappings/UvisMrDischarge.hbm.xml"
							"uvis/dao/mappings/UvisMrDischargeMods.hbm.xml"
							"uvis/dao/mappings/UvisMrDischLtrX2Mods.hbm.xml"
							"uvis/dao/mappings/UvisMrDischLtrXMods.hbm.xml"
							"uvis/dao/mappings/UvisMrEpisodeAddtlInfoX.hbm.xml"
							"uvis/dao/mappings/UvisMrEpisodeDischLtrX2.hbm.xml"
							"uvis/dao/mappings/UvisMrEpisodeDischLtrX.hbm.xml"
							"uvis/dao/mappings/UvisMrEpisodeGrpPatientX.hbm.xml"
							"uvis/dao/mappings/UvisMrEpisodeGrpProfileX.hbm.xml"
							"uvis/dao/mappings/UvisMrEpisode.hbm.xml"
							"uvis/dao/mappings/UvisMrEpisodeProfile.hbm.xml"
							"uvis/dao/mappings/UvisMrEtiologyM.hbm.xml"
							"uvis/dao/mappings/UvisMrEtiologyX.hbm.xml"
							"uvis/dao/mappings/UvisMrExtAreaM.hbm.xml"
							"uvis/dao/mappings/UvisMrGroupRequestX.hbm.xml"
							"uvis/dao/mappings/UvisMrInitialPlan.hbm.xml"
							"uvis/dao/mappings/UvisMrInitialPlanMods.hbm.xml"
							"uvis/dao/mappings/UvisMrInsGuideAreaCatM.hbm.xml"
							"uvis/dao/mappings/UvisMrInsGuideAreaDtl.hbm.xml"
							"uvis/dao/mappings/UvisMrInsGuideAreaHdr.hbm.xml"
							"uvis/dao/mappings/UvisMrInsGuideProdCatM.hbm.xml"
							"uvis/dao/mappings/UvisMrInsGuideProductDtl.hbm.xml"
							"uvis/dao/mappings/UvisMrInsGuideProductHdr.hbm.xml"
							"uvis/dao/mappings/UvisMrInstAddtlInstX.hbm.xml"
							"uvis/dao/mappings/UvisMrInstReqResultX.hbm.xml"
							"uvis/dao/mappings/UvisMrInstructionM.hbm.xml"
							"uvis/dao/mappings/UvisMrItemParams.hbm.xml"
							"uvis/dao/mappings/UvisMrLetter.hbm.xml"
							"uvis/dao/mappings/UvisMrMedication.hbm.xml"
							"uvis/dao/mappings/UvisMrMedicationMods.hbm.xml"
							"uvis/dao/mappings/UvisMrMorphologyM.hbm.xml"
							"uvis/dao/mappings/UvisMrMorphologyX.hbm.xml"
							"uvis/dao/mappings/UvisMrParameters.hbm.xml"
							"uvis/dao/mappings/UvisMrParasiteHistory.hbm.xml"
							"uvis/dao/mappings/UvisMrParasiteHistoryMods.hbm.xml"
							"uvis/dao/mappings/UvisMrParasiteTreatmentX.hbm.xml"
							"uvis/dao/mappings/UvisMrParasiteTypeM.hbm.xml"
							"uvis/dao/mappings/UvisMrParasiteTypeSynX.hbm.xml"
							"uvis/dao/mappings/UvisMrPlanRequestX.hbm.xml"
							"uvis/dao/mappings/UvisMrProblemInstructionX.hbm.xml"
							"uvis/dao/mappings/UvisMrProblemList.hbm.xml"
							"uvis/dao/mappings/UvisMrProblemListMods.hbm.xml"
							"uvis/dao/mappings/UvisMrProblemLog.hbm.xml"
							"uvis/dao/mappings/UvisMrProblemM.hbm.xml"
							"uvis/dao/mappings/UvisMrProblemSpeciesX.hbm.xml"
							"uvis/dao/mappings/UvisMrProblemsV.hbm.xml"
							"uvis/dao/mappings/UvisMrProbRequestX.hbm.xml"
							"uvis/dao/mappings/UvisMrProdlineAreaX.hbm.xml"
							"uvis/dao/mappings/UvisMrProgressNotes.hbm.xml"
							"uvis/dao/mappings/UvisMrProgressNotesMods.hbm.xml"
							"uvis/dao/mappings/UvisMrQueriesV.hbm.xml"
							"uvis/dao/mappings/UvisMrQuery.hbm.xml"
							"uvis/dao/mappings/UvisMrQuestions.hbm.xml"
							"uvis/dao/mappings/UvisMrQuestionsIdenticalX.hbm.xml"
							"uvis/dao/mappings/UvisMrRappCategory.hbm.xml"
							"uvis/dao/mappings/UvisMrRappProducts.hbm.xml"
							"uvis/dao/mappings/UvisMrRappReqItems.hbm.xml"
							"uvis/dao/mappings/UvisMrReqCategoryM.hbm.xml"
							"uvis/dao/mappings/UvisMrRequestAddtlChgs.hbm.xml"
							"uvis/dao/mappings/UvisMrRequestAnswers.hbm.xml"
							"uvis/dao/mappings/UvisMrRequest.hbm.xml"
							"uvis/dao/mappings/UvisMrRequestItems.hbm.xml"
							"uvis/dao/mappings/UvisMrRequestMods.hbm.xml"
							"uvis/dao/mappings/UvisMrRequestStatusLog.hbm.xml"
							"uvis/dao/mappings/UvisMrRequestV.hbm.xml"
							"uvis/dao/mappings/UvisMrResultAnswers.hbm.xml"
							"uvis/dao/mappings/UvisMrResultAnswersMods.hbm.xml"
							"uvis/dao/mappings/UvisMrResult.hbm.xml"
							"uvis/dao/mappings/UvisMrResultMods.hbm.xml"
							"uvis/dao/mappings/UvisMrSoapComment.hbm.xml"
							"uvis/dao/mappings/UvisMrSoapCommentMods.hbm.xml"
							"uvis/dao/mappings/UvisMrStandardCommentM.hbm.xml"
							"uvis/dao/mappings/UvisMrSubdatatype.hbm.xml"
							"uvis/dao/mappings/UvisMrVaccineHistory.hbm.xml"
							"uvis/dao/mappings/UvisMrVaccineHistoryMods.hbm.xml"
							"uvis/dao/mappings/UvisMrVerifyParams.hbm.xml"
							"uvis/dao/mappings/UvisMrVerifyTracking.hbm.xml"
							"uvis/dao/mappings/UvisMrVerifyTypeM.hbm.xml"
							"uvis/dao/mappings/UvisMrVisit.hbm.xml"
							"uvis/dao/mappings/UvisMrVitalSigns.hbm.xml"
							"uvis/dao/mappings/UvisMrVitalSignsMods.hbm.xml"
							"uvis/dao/mappings/UvisOpenDirectOrdersV.hbm.xml"
							"uvis/dao/mappings/UvisOrderDtl.hbm.xml"
							"uvis/dao/mappings/UvisOrderDtlH.hbm.xml"
							"uvis/dao/mappings/UvisOrderDtlInvLog.hbm.xml"
							"uvis/dao/mappings/UvisOrderDtlLogAllV.hbm.xml"
							"uvis/dao/mappings/UvisOrderDtlLog.hbm.xml"
							"uvis/dao/mappings/UvisOrderDtlTaxX.hbm.xml"
							"uvis/dao/mappings/UvisOrderHdr.hbm.xml"
							"uvis/dao/mappings/UvisOrderHdrH.hbm.xml"
							"uvis/dao/mappings/UvisOrderHdrLogAllV.hbm.xml"
							"uvis/dao/mappings/UvisOrderHdrLog.hbm.xml"
							"uvis/dao/mappings/UvisOrderItemStatusM.hbm.xml"
							"uvis/dao/mappings/UvisOrderStatusM.hbm.xml"
							"uvis/dao/mappings/UvisOrderTypeM.hbm.xml"
							"uvis/dao/mappings/UvisOrderTypeOptionsM.hbm.xml"
							"uvis/dao/mappings/UvisOrderTypeOptionsSetM.hbm.xml"
							"uvis/dao/mappings/UvisOrderTypeOptionsSetX.hbm.xml"
							"uvis/dao/mappings/UvisOrderUnitM.hbm.xml"
							"uvis/dao/mappings/UvisPatientAlertM.hbm.xml"
							"uvis/dao/mappings/UvisPatientAlertX.hbm.xml"
							"uvis/dao/mappings/UvisPatientContactTypeM.hbm.xml"
							"uvis/dao/mappings/UvisPatientContactX.hbm.xml"
							"uvis/dao/mappings/UvisPatientGroupX.hbm.xml"
							"uvis/dao/mappings/UvisPatient.hbm.xml"
							"uvis/dao/mappings/UvisPatientLog.hbm.xml"
							"uvis/dao/mappings/UvisPatientOncologyDtl.hbm.xml"
							"uvis/dao/mappings/UvisPatientRdvmDistinctV.hbm.xml"
							"uvis/dao/mappings/UvisPatientRdvmX.hbm.xml"
							"uvis/dao/mappings/UvisPatientReminders.hbm.xml"
							"uvis/dao/mappings/UvisPatientRemindersLog.hbm.xml"
							"uvis/dao/mappings/UvisPatientTags.hbm.xml"
							"uvis/dao/mappings/UvisPatientTagTypeM.hbm.xml"
							"uvis/dao/mappings/UvisPatientTxLog.hbm.xml"
							"uvis/dao/mappings/UvisPaymentTypeM.hbm.xml"
							"uvis/dao/mappings/UvisPcReorderWorking.hbm.xml"
							"uvis/dao/mappings/UvisPdSetup.hbm.xml"
							"uvis/dao/mappings/UvisPendingCsAssembly.hbm.xml"
							"uvis/dao/mappings/UvisPendingCsAssemblyL3.hbm.xml"
							"uvis/dao/mappings/UvisPendingCsRequestDtl.hbm.xml"
							"uvis/dao/mappings/UvisPendingCsRequestHdr.hbm.xml"
							"uvis/dao/mappings/UvisPendingInvRequest.hbm.xml"
							"uvis/dao/mappings/UvisPendingInvXfer.hbm.xml"
							"uvis/dao/mappings/UvisPendingPhRequest.hbm.xml"
							"uvis/dao/mappings/UvisPersonnelSchd.hbm.xml"
							"uvis/dao/mappings/UvisPhAdminister.hbm.xml"
							"uvis/dao/mappings/UvisPhAdministrationUnitM.hbm.xml"
							"uvis/dao/mappings/UvisPhAgeRules.hbm.xml"
							"uvis/dao/mappings/UvisPhAlertsM.hbm.xml"
							"uvis/dao/mappings/UvisPhAlertsTypeM.hbm.xml"
							"uvis/dao/mappings/UvisPharmacyAddress.hbm.xml"
							"uvis/dao/mappings/UvisPharmacyM.hbm.xml"
							"uvis/dao/mappings/UvisPharmacySetup.hbm.xml"
							"uvis/dao/mappings/UvisPhBreedRules.hbm.xml"
							"uvis/dao/mappings/UvisPhCdmM.hbm.xml"
							"uvis/dao/mappings/UvisPhCdmProductsM.hbm.xml"
							"uvis/dao/mappings/UvisPhCdmStockX.hbm.xml"
							"uvis/dao/mappings/UvisPhCompoundDtl.hbm.xml"
							"uvis/dao/mappings/UvisPhCompoundHdr.hbm.xml"
							"uvis/dao/mappings/UvisPhControlSubLog.hbm.xml"
							"uvis/dao/mappings/UvisPhControlSubLogV.hbm.xml"
							"uvis/dao/mappings/UvisPhCsWastage.hbm.xml"
							"uvis/dao/mappings/UvisPhCsWastageLog.hbm.xml"
							"uvis/dao/mappings/UvisPhDiagnosisRules.hbm.xml"
							"uvis/dao/mappings/UvisPhDosageM.hbm.xml"
							"uvis/dao/mappings/UvisPhDurationM.hbm.xml"
							"uvis/dao/mappings/UvisPhEmployeeCdmLog.hbm.xml"
							"uvis/dao/mappings/UvisPhErrorLog.hbm.xml"
							"uvis/dao/mappings/UvisPhErrorM.hbm.xml"
							"uvis/dao/mappings/UvisPhFrequencyM.hbm.xml"
							"uvis/dao/mappings/UvisPhGenericDrugInfo.hbm.xml"
							"uvis/dao/mappings/UvisPhGenericM.hbm.xml"
							"uvis/dao/mappings/UvisPhInfoCategoryM.hbm.xml"
							"uvis/dao/mappings/UvisPhInteractions.hbm.xml"
							"uvis/dao/mappings/UvisPhProductGenericX.hbm.xml"
							"uvis/dao/mappings/UvisPhProductRouteX.hbm.xml"
							"uvis/dao/mappings/UvisPhRouteM.hbm.xml"
							"uvis/dao/mappings/UvisPhRxAlertLog.hbm.xml"
							"uvis/dao/mappings/UvisPhRxExtPatient.hbm.xml"
							"uvis/dao/mappings/UvisPhRxInvX.hbm.xml"
							"uvis/dao/mappings/UvisPhRxLabelM.hbm.xml"
							"uvis/dao/mappings/UvisPhRxLabelProductX.hbm.xml"
							"uvis/dao/mappings/UvisPhRxProductHold.hbm.xml"
							"uvis/dao/mappings/UvisPhVerbM.hbm.xml"
							"uvis/dao/mappings/UvisPhWeightRules.hbm.xml"
							"uvis/dao/mappings/UvisPickCategoryM.hbm.xml"
							"uvis/dao/mappings/UvisPickSheet.hbm.xml"
							"uvis/dao/mappings/UvisPickSheetTitleM.hbm.xml"
							"uvis/dao/mappings/UvisPickSheetTypeM.hbm.xml"
							"uvis/dao/mappings/UvisPoDtl.hbm.xml"
							"uvis/dao/mappings/UvisPoDtlReceivingLog.hbm.xml"
							"uvis/dao/mappings/UvisPoHdrAlphaV.hbm.xml"
							"uvis/dao/mappings/UvisPoHdr.hbm.xml"
							"uvis/dao/mappings/UvisPoRecordType.hbm.xml"
							"uvis/dao/mappings/UvisPoStatusM.hbm.xml"
							"uvis/dao/mappings/UvisPoTypeM.hbm.xml"
							"uvis/dao/mappings/UvisPrescriptionAudit.hbm.xml"
							"uvis/dao/mappings/UvisPrescriptionEmpV.hbm.xml"
							"uvis/dao/mappings/UvisPrescription.hbm.xml"
							"uvis/dao/mappings/UvisPrescriptionH.hbm.xml"
							"uvis/dao/mappings/UvisPrescriptionLogAudit.hbm.xml"
							"uvis/dao/mappings/UvisPrescriptionLog.hbm.xml"
							"uvis/dao/mappings/UvisPrescriptionLogMod.hbm.xml"
							"uvis/dao/mappings/UvisPrescriptionX.hbm.xml"
							"uvis/dao/mappings/UvisPriceLevelM.hbm.xml"
							"uvis/dao/mappings/UvisPricingTypeM.hbm.xml"
							"uvis/dao/mappings/UvisPrimaryDiagInstX.hbm.xml"
							"uvis/dao/mappings/UvisPrimaryDiagnosisM.hbm.xml"
							"uvis/dao/mappings/UvisPrinterM.hbm.xml"
							"uvis/dao/mappings/UvisProcedureM.hbm.xml"
							"uvis/dao/mappings/UvisProcPullsM.hbm.xml"
							"uvis/dao/mappings/UvisProductAssembly.hbm.xml"
							"uvis/dao/mappings/UvisProductCategoryM.hbm.xml"
							"uvis/dao/mappings/UvisProductGenericTypeM.hbm.xml"
							"uvis/dao/mappings/UvisProductGenericV.hbm.xml"
							"uvis/dao/mappings/UvisProduct.hbm.xml"
							"uvis/dao/mappings/UvisProductLineM.hbm.xml"
							"uvis/dao/mappings/UvisProductRepairH.hbm.xml"
							"uvis/dao/mappings/UvisProductRepairHV.hbm.xml"
							"uvis/dao/mappings/UvisProductSynonym.hbm.xml"
							"uvis/dao/mappings/UvisProductTypeM.hbm.xml"
							"uvis/dao/mappings/UvisProductUsageH.hbm.xml"
							"uvis/dao/mappings/UvisProratedDistributionM.hbm.xml"
							"uvis/dao/mappings/UvisProratedServiceAreas.hbm.xml"
							"uvis/dao/mappings/UvisQueryV.hbm.xml"
							"uvis/dao/mappings/UvisReferralCcardInfo.hbm.xml"
							"uvis/dao/mappings/UvisReferralInfoAlertX.hbm.xml"
							"uvis/dao/mappings/UvisReferralInfo.hbm.xml"
							"uvis/dao/mappings/UvisReferralSourceM.hbm.xml"
							"uvis/dao/mappings/UvisRegisterLog.hbm.xml"
							"uvis/dao/mappings/UvisRegisterTotals.hbm.xml"
							"uvis/dao/mappings/UvisReminderCategoryM.hbm.xml"
							"uvis/dao/mappings/UvisReminderM.hbm.xml"
							"uvis/dao/mappings/UvisReminderSpeciesCatM.hbm.xml"
							"uvis/dao/mappings/UvisReorderWorking.hbm.xml"
							"uvis/dao/mappings/UvisReorderWorkingV.hbm.xml"
							"uvis/dao/mappings/UvisRepairSummaryV.hbm.xml"
							"uvis/dao/mappings/UvisRoleM.hbm.xml"
							"uvis/dao/mappings/UvisRoleModulePrivX.hbm.xml"
							"uvis/dao/mappings/UvisRoleModuleX.hbm.xml"
							"uvis/dao/mappings/UvisRoleRoleX.hbm.xml"
							"uvis/dao/mappings/UvisRoleTableX.hbm.xml"
							"uvis/dao/mappings/UvisSalesUnitM.hbm.xml"
							"uvis/dao/mappings/UvisSchdApptTypeM.hbm.xml"
							"uvis/dao/mappings/UvisSchdAreaM.hbm.xml"
							"uvis/dao/mappings/UvisSchdAreaSchd.hbm.xml"
							"uvis/dao/mappings/UvisSchdDayM.hbm.xml"
							"uvis/dao/mappings/UvisSchdDtl.hbm.xml"
							"uvis/dao/mappings/UvisSchdEndingV.hbm.xml"
							"uvis/dao/mappings/UvisSchdFunctionM.hbm.xml"
							"uvis/dao/mappings/UvisSchdHdr.hbm.xml"
							"uvis/dao/mappings/UvisSchdResponsibilityM.hbm.xml"
							"uvis/dao/mappings/UvisSchdTemplateDtl.hbm.xml"
							"uvis/dao/mappings/UvisSchdTemplateHdr.hbm.xml"
							"uvis/dao/mappings/UvisSchdTypeM.hbm.xml"
							"uvis/dao/mappings/UvisScriptErrorLog.hbm.xml"
							"uvis/dao/mappings/UvisScript.hbm.xml"
							"uvis/dao/mappings/UvisScriptModule.hbm.xml"
							"uvis/dao/mappings/UvisServiceAreaM.hbm.xml"
							"uvis/dao/mappings/UvisServiceAreaSections.hbm.xml"
							"uvis/dao/mappings/UvisSeSetup.hbm.xml"
							"uvis/dao/mappings/UvisSexM.hbm.xml"
							"uvis/dao/mappings/UvisShiftM.hbm.xml"
							"uvis/dao/mappings/UvisSlidingScaleM.hbm.xml"
							"uvis/dao/mappings/UvisSlidingScaleRanges.hbm.xml"
							"uvis/dao/mappings/UvisSpeciesM.hbm.xml"
							"uvis/dao/mappings/UvisSpeciesParasiteX.hbm.xml"
							"uvis/dao/mappings/UvisSpeciesQuestionX.hbm.xml"
							"uvis/dao/mappings/UvisSpeciesVaccineX.hbm.xml"
							"uvis/dao/mappings/UvisStateM.hbm.xml"
							"uvis/dao/mappings/UvisStockUnitM.hbm.xml"
							"uvis/dao/mappings/UvisSupportStaffX.hbm.xml"
							"uvis/dao/mappings/UvisSysOptionsCatM.hbm.xml"
							"uvis/dao/mappings/UvisSysOptionsM.hbm.xml"
							"uvis/dao/mappings/UvisSysOptionsModuleX.hbm.xml"
							"uvis/dao/mappings/UvisSysOptionsSetM.hbm.xml"
							"uvis/dao/mappings/UvisSysOptionsSetX.hbm.xml"
							"uvis/dao/mappings/UvisSystemErrorLog.hbm.xml"
							"uvis/dao/mappings/UvisSystemErrorsM.hbm.xml"
							"uvis/dao/mappings/UvisSystemLocationM.hbm.xml"
							"uvis/dao/mappings/UvisSystemM.hbm.xml"
							"uvis/dao/mappings/UvisSystemSetup.hbm.xml"
							"uvis/dao/mappings/UvisSystemUserM.hbm.xml"
							"uvis/dao/mappings/UvisTableM.hbm.xml"
							"uvis/dao/mappings/UvisTableUserV.hbm.xml"
							"uvis/dao/mappings/UvisTagsM.hbm.xml"
							"uvis/dao/mappings/UvisTagsX.hbm.xml"
							"uvis/dao/mappings/UvisTailoredPulls.hbm.xml"
							"uvis/dao/mappings/UvisTaxRateM.hbm.xml"
							"uvis/dao/mappings/UvisTaxTypeM.hbm.xml"
							"uvis/dao/mappings/UvisTestM.hbm.xml"
							"uvis/dao/mappings/UvisTestModuleV.hbm.xml"
							"uvis/dao/mappings/UvisTestResult.hbm.xml"
							"uvis/dao/mappings/UvisTitleM.hbm.xml"
							"uvis/dao/mappings/UvisTransferProductV.hbm.xml"
							"uvis/dao/mappings/UvisUserNotification.hbm.xml"
							"uvis/dao/mappings/UvisUserNotificationStatM.hbm.xml"
							"uvis/dao/mappings/UvisUserNotificationTypeM.hbm.xml"
							"uvis/dao/mappings/UvisUserOptions.hbm.xml"
							"uvis/dao/mappings/UvisUserOptionsM.hbm.xml"
							"uvis/dao/mappings/UvisUserOptionsSetM.hbm.xml"
							"uvis/dao/mappings/UvisUserOptionsSetVals.hbm.xml"
							"uvis/dao/mappings/UvisUserToolbar.hbm.xml"
							"uvis/dao/mappings/UvisVendor.hbm.xml"
							"uvis/dao/mappings/UvisVendorProducts.hbm.xml"
							"uvis/dao/mappings/UvisVendorProductsH.hbm.xml"
							"uvis/dao/mappings/UvisVendorRepairProducts.hbm.xml"
							"uvis/dao/mappings/UvisWorkingPaws.hbm.xml"
							"uvis/dao/mappings/UvisZipCode.hbm.xml"
							"uvis/dao/mappings/UvisZipFormatM.hbm.xml")}
  :post (fn [x] (.postCreate x)))



